Repository TellmeMarket/Market-Kalry, pull requests merged in 2023-02, with the labels that each got.

#42 [feat] 제품 리스트 페이지 완성
  .prettierrc.js
  client/.prettierrc
  client/assets/header/new1.svg
  client/assets/icons/Icon/Direction=Down.svg
  client/assets/icons/Icon/Direction=Right.svg
  client/assets/icons/Icon/pre-pre.svg
  client/assets/icons/Icon/pre.svg
  client/assets/icons/Input/isChecked=false.svg
  client/assets/icons/Input/isChecked=true.png
  client/components/header-footer/headerfooter.css
  client/components/product-detail/productDetail.html
  client/components/product-list/productList.html
  client/css/style-productList.css
Labels: feat

#49 [style] 상세페이지 코드와 스타일 변경 및 css 코딩 컨벤션 적용
  .vscode/settings.json
  client/assets/product-detail/Notice.png
  client/components/product-detail/productDetail.css
  client/components/product-detail/productDetail.html
Labels: refactor, Document

#54 [feat] 최근 본 상품 기능 추가
  client/components/product-detail/productDetail.html
  client/css/style.css
  client/index.html
  client/js/main.js
Labels: feat, Document

#57 [feat] 장바구니 버블 창 추가
  client/components/header-footer/headerFooter.css
  client/index.html
  client/js/main.js
Labels: feat, refactor
